### ISSUE TITLE
Add some distinction to commands typed by the user and their output.

### ISSUE THREAD

**Issue by Mm2PL** [tsoding/something#205]
Currently there is no way to see what is the command the user typed into the console, thus it's hard to see what's the output of a command and the user's input and another command's output.

Example:
```
help
help - Print this help
reset - Reset the state of the entities
spawn_enemy - Spawn an enemy
close - Close the console
set - Set the value of a variable
reload - Reloads the configuration file
save_room - Save the current room as new file
history - Print the history of the Console
reload
Reloaded config file `./assets/config.vars`
```
This feels like a mess.

While this doesn't looks like so much of a mess:

```
>> help
help - Print this help
reset - Reset the state of the entities
spawn_enemy - Spawn an enemy
close - Close the console
set - Set the value of a variable
reload - Reloads the configuration file
save_room - Save the current room as new file
history - Print the history of the Console

>> reload
Reloaded config file `./assets/config.vars`
```
Using colors or different fonts to achieve this distinction would be harder but would look a bit better.

**Comment by rexim** [comment]
@Mm2PL I tried to address the problem in #207. Please close the issue if the PR fixed it.

**Comment by Mm2PL** [comment]
That works for me :slightly_smiling_face:
