### ISSUE TITLE
Camera movement don't update mouse position in the world

### ISSUE THREAD

**Issue by kolumb** [tsoding/something#259]
![2020-11-01 18-47-14-min](https://user-images.githubusercontent.com/4366033/97809247-7d5d9080-1c74-11eb-8337-2988c98af44f.gif)

**Comment by rexim** [comment]
The idea solution would be to update `Game::mouse_position` in a way described in  https://bugzilla.libsdl.org/show_bug.cgi?id=2442#c2 But that is not enough. You also need to detect when `Camera::pos` is update and update `Game::mouse_position` accordingly.

**Comment by rexim** [comment]
@kolumb should be addressed by #273. Please close the issue if it works for you on the latest version.

**Comment by kolumb** [comment]
@rexim branch `259` was not merged in `master` branch.

**Comment by rexim** [comment]
@kolumb fixed! Thank you so much for letting me know! :)
