### ISSUE TITLE
Document minimal dependency versions

### ISSUE THREAD

**Issue by rexim** [tsoding/something#26]
> ThorsLostKitten: @Tsoding figured it out, I was defaulting to g++ 5, using 7.4.0 fixes some issues. the rest was fixed by specifying libpng16-dev explicitely (had libpng12-dev by default) - so my system was just outdated

**Comment by JaroslawWiosna** [comment]
Probably already resolved by #239

**Comment by kolumb** [comment]
But `libpng` is not used by current version of "Something".
