### ISSUE TITLE
SDLK_BACKQUOTE don't work on PTBR keyboard

### ISSUE THREAD

**Issue by drocha87** [tsoding/something#278]
When using PTBR (Brazilian portuguese) keyboards, to generate a `SDLK_BACKQUOTE` we need to press a combination of `shift+'+space`.

In debug mode to toggle console, these keys combination don't work as it conflicts with other commands like the `space` to jump. 
I suggest to change the console toggle shortcut to `SDLK_BACKSLASH` since I don't think it conflict with other shortcut in the game.

It's a minimal change, but will make my life easier to toggle console :stuck_out_tongue: .

**Comment by rexim** [comment]
@drocha87 sure! I'm ok with backslash! :)

**Comment by kolumb** [comment]
Someone in twitch chat suggested:
> Kiskiss: why replace, just have multiple ways?
