### ISSUE TITLE
Projéctile animation is shared among all of them

### ISSUE THREAD

**Issue by kolumb** [tsoding/something#279]
### Steps to reproduce:
1. Change config variable `ENTITY_COOLDOWN_WEAPON` to 0.01
1. Enter step-debug mode
1. Shot
1. Press `X`
1. Repeat from step 3

### Observed
![Без-имени-1](https://user-images.githubusercontent.com/4366033/99157498-fa0b5880-26d1-11eb-98f2-bb26d51b1c3f.jpg)

All projéctiles have the same frame. It's not that much noticeable in `Idle` state. But it's bad for `Poof` state: in regular gameplay you not always see poof animation.
### Expected
Separate animation cycles for each projéctile.

**Comment by kolumb** [comment]
Solved by #298

**Comment by rexim** [comment]
@kolumb thank you so much for checking it! Forgot to drop a comment here! :D
