### ISSUE TITLE
window too small

### ISSUE THREAD

**Issue by Frank-Buss** [tsoding/something#98]
When I start the game on my Debian system, it looks like this:
https://i.imgur.com/twrpWI3.png
Probably the window is too small.

**Comment by zhiayang** [comment]
are you running on a high-dpi display? or running with some kind of display scaling?

**Comment by Frank-Buss** [comment]
@zhiayang The problem is only in window mode, works in fullscreen. I think the initial size of the window should be a fraction of the screen size. Then SDL_RenderSetScale(renderer, scaleX, scaleY) can be used to scale the image. Shouldn't influence the speed, at least not in Linux, because OpenGL is used and the scaling should be done on the graphics card.

Might be also a good idea to detect window scale events and then adjust the scale. And maybe save the last window size and position in an init file on program exit, which then is read on the next start.

I just tried SDL_RenderSetScale(renderer, scaleX, scaleY) with a factor of 0.5f, but looks like sometimes there are problems at the boundaries of the tiles, maybe because it is not pixel perfect when scaled. In Unity there is a solution for it:

https://docs.unity3d.com/Packages/com.unity.2d.pixel-perfect@1.0/manual/index.html

Might be interesting to re-implement this with SDL, only. Or just forget this bug report and start the game always in fullscreen with the right resolution.

**Comment by rexim** [comment]
Resolved by #124
